from . import rm_forces
from . import rm_ranks
from . import rm_rules_category
from . import rm_product_sync_mixin
from . import rm_decoration
from . import prb
from . import attachments
from . import rm_unit_category
from . import rm_unit
from . import res_person
from . import bcs_batch
from . import rm_personal_award
from . import posting_mision
from . import rm_excluded_award
from . import rm_acquisition
from . import rm_acquisition_custom
from . import mrp_production
from . import rm_component_category
from . import rm_set_template
from . import rm_set_order_line
from . import rm_set_order
from . import rm_rack_line
from . import rm_rack_product
from . import rm_person_search_wizard
from . import rm_sale_line_person_wizard
from . import rm_partner_to_person_wizard
from . import sale_order
