from . import rm_forces
from . import rm_ranks
from . import rm_rules_category
from . import rm_decoration
from . import prb
from . import attachments
from . import rm_unit_category
from . import rm_unit
from . import res_person
from . import bcs_batch
from . import rm_personal_award
from . import posting_mision
from . import rm_excluded_award
from . import rm_acquisition
from . import rm_acquisition_custom
